
services:
  - type: web
    name: insta-link-bot-backend
    env: python
    buildCommand: ""
    startCommand: "gunicorn app:app"
    plan: free
    envVars:
      - key: STRIPE_SECRET_KEY
        sync: false
